name: angular_dart_examples
version: 0.0.1
dependencies:
  angular: "1.1.2+2"
  web_components: "0.10.1"
  browser: ">=0.10.0+2 <0.11.0"
  dart_to_js_script_rewriter: ^0.1.0
dev_dependencies:
  dartmocks: ">= 0.5.0"
  guinness: ">=0.1.5 <0.2.0"
transformers:
- angular
- dart_to_js_script_rewriter